# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31114f770861b028a279a48cc872d583b22cf4a7b1b991d32dc96e9282584e886131c9f0768a51499dd9532de8a7eae1baa870338c0e7a681b4729b2401ea914

test:
  secret_key_base: f72edb6897d9e3b36ef572a9db5693fdcf1fa5edd48c8266da008a27be1a6c2494f12d675f76ee27a733ba4c3de44af00e40b04f500034ca35aa21fbba49feb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
